spring.application.name=naina-artistry

spring.datasource.url=jdbc:postgresql://localhost:5432/naina_artistry
spring.datasource.username=postgres
spring.datasource.password=Root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true